version: '3'
services:
  backend:
      build:
        context: .
      ports:
        - 5000:5000
      environment:
        MYSQL_HOST: mysql
        MYSQL_USER: tushar
        MYSQL_PASSWORD: test@123
        MYSQL_DB: two_tier
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_USER: tushar
      MYSQL_PASSWORD: test@123
      MYSQL_DATABASE: two_tier

        
