version: '3'
services:
  backend:
      build:
        context: .
      ports:
        - 5000:5000
      environment:
        MYSQL_HOST: mysql
        MYSQL_USER: tushar
        MYSQL_PASSWORD: test@123
        MYSQL_DB: two_tier
      depends_on:
        - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_USER: tushar
      MYSQL_PASSWORD: test@123
      MYSQL_DATABASE: two_tier
    volumes: 
      - two_tier_vol:/var/lib/mysql
      - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
volumes:
  two_tier_vol:

        
